repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka
    namespace: default
    chart: bitnami/kafka
    values:
      - values-kafka.yaml

  - name: redis
    namespace: default
    chart: bitnami/redis
    values:
      - values-redis.yaml
