enabled: true
clusterDomain: cluster.local
heapOpts: -Xmx1024m -Xms1024m

controller:
  replicaCount: 0
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

broker:
  replicaCount: 3
  statefulSet:
    enabled: true
  minId: 100
  zookeeperMigrationMode: false
  heapOpts: -Xmx1024m -Xms1024m
  automountServiceAccountToken: true
  updateStrategy:
    type: RollingUpdate
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi
    mountPath: /bitnami/kafka
  logPersistence:
    enabled: false
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    mountPath: /opt/bitnami/kafka/logs
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

kraft:
  enabled: false
zookeeper:
  enabled: true
  replicaCount: 3
  auth:
    client:
      enabled: false
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  # externalZookeeper:
  # servers:
  #   - "zookeeper-0.kafka.svc.cluster.local:2181"
  #   - "zookeeper-1.kafka.svc.cluster.local:2181"
  #   - "zookeeper-2.kafka.svc.cluster.local:2181"

externalAccess:
  enabled: true
  broker:
    service:
      type: NodePort
      nodePorts:
        - 30066
        - 30067
        - 30068
      externalIPs:
        - 192.168.49.201
        - 192.168.49.202
        - 192.168.49.203

  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT

networkPolicy:
  enabled: true
  allowExternal: true
