kafka:
  enabled: true
  controller:
    replicaCount: 0
    automountServiceAccountToken: true
  broker:
    replicaCount: 3
    persistence:
      size: 10Gi
    automountServiceAccountToken: true
  kraft:
    enabled: false
  zookeeper:
    enabled: true
    persistence:
      size: 10Gi
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
    configuration:
  externalAccess:
    enabled: true
    broker:
      service:
        type: NodePort
        nodePorts:
          - 30066
          - 30067
          - 30068
        externalIPs:
        - 192.168.49.201
        - 192.168.49.202
        - 192.168.49.203




redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi
  replica:
    replicaCount: 3  
    persistence:
      enabled: true
      size: 8Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis-replica  
      ##      topologyKey: "kubernetes.io/hostname"  # TODO

  sentinel:
    enabled: true  
    masterSet: "mymaster"  
    persistence:
      enabled: true
      size: 8Gi
    sentinelCount: 3
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis-sentinel  
            ## topologyKey: "kubernetes.io/hostname"  #TODO

