kafka:
  enabled: true
  image:
    debug: true
  controller:
    replicaCount: 0
    automountServiceAccountToken: true
    resources:
      requests:
        cpu: "100m"           
        memory: "256Mi"      
      limits:
        cpu: "200m"          
        memory: "512Mi"
  broker:
    replicaCount: 3
    persistence:
      size: 10Gi
    automountServiceAccountToken: true
    resources:
      requests:
        cpu: "100m"           
        memory: "256Mi"      
      limits:
        cpu: "200m"          
        memory: "512Mi"
  kraft:
    enabled: false
  listeners:
    client:
      protocol: SSL
      sslClientAuth: required
    controller:
      protocol: SSL
      sslClientAuth: required
    interbroker:
      protocol: SSL
      sslClientAuth: required
    external:
      protocol: SSL
      sslClientAuth: required
  tls:
    type: JKS
    existingSecret: kafka-jks
    keystorePassword: changeit
    truststorePassword: changeit
    zookeeper:
      enabled: true
      existingSecret: zookeeper-jks
      keystorePassword: changeit
      truststorePassword: changeit
  externalAccess:
    enabled: true
    broker:
      service:
        type: NodePort
        nodePorts:
          - 30066
          - 30067
          - 30068
        externalIPs:
        - 192.168.49.201
        - 192.168.49.202 
        - 192.168.49.203
  zookeeper:
    enabled: true
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: "100m"           
        memory: "256Mi"      
      limits:
        cpu: "200m"          
        memory: "512Mi"
    tls:
      client:
        enabled: true
        auth: need
        existingSecret: zookeeper-jks
        keystorePassword: changeit
        truststorePassword: changeit
      quorum:
        enabled: true
        auth: need
        existingSecret: zookeeper-jks
        keystorePassword: changeit
        truststorePassword: changeit
    networkPolicy:
      enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi
      resources:
    requests:
        cpu: "100m"           
        memory: "256Mi"      
      limits:
        cpu: "200m"          
        memory: "512Mi"
  replica:
    replicaCount: 3  
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: "100m"           
        memory: "256Mi"      
      limits:
        cpu: "200m"          
        memory: "512Mi"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: app
    #               operator: In
    #               values:
    #                 - redis-replica  
      ##      topologyKey: failure-domain.beta.kubernetes.io/zone  # TODO

  sentinel:
    enabled: true  
    masterSet: "mymaster"  
    persistence:
      enabled: true
      size: 8Gi
    sentinelCount: 3
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchExpressions:
    #             - key: app
    #               operator: In
    #               values:
    #                 - redis-sentinel  
            ## topologyKey: failure-domain.beta.kubernetes.io/zone  #TODO